name: Deploy QR Code Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test
        
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          PORT: ${{ secrets.PORT }}
          NODE_ENV: production
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          UPLOAD_DIR: uploads
          MAX_FILE_SIZE: ${{ secrets.MAX_FILE_SIZE }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: PORT,NODE_ENV,MONGODB_URI,UPLOAD_DIR,MAX_FILE_SIZE,SESSION_SECRET,ADMIN_USERNAME,ADMIN_PASSWORD
          script: |
            cd /home/ubuntu/Two-dimensional-code
            git pull origin main
            npm install
            
            # 创建或更新 .env 文件
            echo "PORT=${PORT}" > .env
            echo "NODE_ENV=${NODE_ENV}" >> .env
            echo "MONGODB_URI=${MONGODB_URI}" >> .env
            echo "UPLOAD_DIR=${UPLOAD_DIR}" >> .env
            echo "MAX_FILE_SIZE=${MAX_FILE_SIZE}" >> .env
            echo "SESSION_SECRET=${SESSION_SECRET}" >> .env
            echo "ADMIN_USERNAME=${ADMIN_USERNAME}" >> .env
            echo "ADMIN_PASSWORD=${ADMIN_PASSWORD}" >> .env
            
            # 重启应用
            pm2 restart qrcode-app || pm2 start index.js --name qrcode-app 